trigger:
  branches:
    include:
      - main  # Trigger pipeline on 'main' branch (change as needed)

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureWebAppName: 'angular-demo-app'  # Your Azure Web App name
  azureResourceGroup: 'angular'  # Your Azure Resource Group name

stages:
  - stage: Build
    displayName: 'Build Angular Application'
    jobs:
      - job: BuildJob
        displayName: 'Build Job'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'  # Specify Node.js version
            displayName: 'Install Node.js'

          - script: |
              npm install -g pnpm
              pnpm install
            displayName: 'Install dependencies'

          - script: |
              pnpm run build --configuration production
            displayName: 'Build Angular Application'

          # Publish the build output as an artifact
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(System.DefaultWorkingDirectory)/dist/angular-demo'  # Path to the build output folder
              ArtifactName: 'angular-artifact'  # The name of the artifact
              publishLocation: 'Container'
            displayName: 'Publish Artifact'
